// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9SG2NW_6KK0JsY-66PCRoYJ1rNR45fQ',
    appId: '1:825797100274:web:16477693e548aeb708c66b',
    messagingSenderId: '825797100274',
    projectId: 'kafe-sri-rahajoe',
    authDomain: 'kafe-sri-rahajoe.firebaseapp.com',
    databaseURL: 'https://kafe-sri-rahajoe-default-rtdb.firebaseio.com',
    storageBucket: 'kafe-sri-rahajoe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSqKN4bS5eefzJrw1y5cC17a4tSoi50U',
    appId: '1:825797100274:android:9ac2ca4fe1a483b008c66b',
    messagingSenderId: '825797100274',
    projectId: 'kafe-sri-rahajoe',
    databaseURL: 'https://kafe-sri-rahajoe-default-rtdb.firebaseio.com',
    storageBucket: 'kafe-sri-rahajoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfs-7d6sdmNrCvxNdGQsrmsXqPVdwFXs',
    appId: '1:825797100274:ios:4c65e179e49c42b708c66b',
    messagingSenderId: '825797100274',
    projectId: 'kafe-sri-rahajoe',
    databaseURL: 'https://kafe-sri-rahajoe-default-rtdb.firebaseio.com',
    storageBucket: 'kafe-sri-rahajoe.firebasestorage.app',
    iosBundleId: 'com.example.kafeBaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQfs-7d6sdmNrCvxNdGQsrmsXqPVdwFXs',
    appId: '1:825797100274:ios:4c65e179e49c42b708c66b',
    messagingSenderId: '825797100274',
    projectId: 'kafe-sri-rahajoe',
    databaseURL: 'https://kafe-sri-rahajoe-default-rtdb.firebaseio.com',
    storageBucket: 'kafe-sri-rahajoe.firebasestorage.app',
    iosBundleId: 'com.example.kafeBaru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-9SG2NW_6KK0JsY-66PCRoYJ1rNR45fQ',
    appId: '1:825797100274:web:5ae58496872c0c5008c66b',
    messagingSenderId: '825797100274',
    projectId: 'kafe-sri-rahajoe',
    authDomain: 'kafe-sri-rahajoe.firebaseapp.com',
    databaseURL: 'https://kafe-sri-rahajoe-default-rtdb.firebaseio.com',
    storageBucket: 'kafe-sri-rahajoe.firebasestorage.app',
  );

}